title: ManaBreak Studios
tagline: a gamedev indie studio
email: alexandru.pana@manabreakstudios.com
description: >
  Indie game development studio from Romania
baseurl: ""
url: ""
paginate:         1

# About/contact
author:
  name:              Alexandru Pana
  url:               https://alexpana.net
  email:             astronothing@gmail.com

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock

# Permalinks
permalink:           pretty

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed
